apiVersion: tekton.dev/v1alpha1
kind: Pod
metadata:
  name: bretfish
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__