apiVersion: apps/v1
kind: Deployment
metadata:
  name: bretfish
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__